In [52]:
import cv2
import numpy as np
import math
import matplotlib.pyplot as plt


img = cv2.imread("DSC_9915.JPG")
img = cv2.resize(img,(500,400))
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# img = np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13],[13,14,15,16,17],[17,18,19,20,21],[21,22,23,24,25]])

# cv2.imshow("img",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

m,n = img.shape[0],img.shape[1]
r = math.ceil(min(m,n)/2)
print(img)
print(m,n)

[[ 13  10   9 ...  16   8  15]
 [ 15  19  13 ...  17  10  13]
 [ 14  18  10 ...   9  12  16]
 ...
 [ 55  12  23 ...  77  73  92]
 [ 57   2  18 ...  77  89  86]
 [ 44   8  21 ... 103  83  73]]
400 500


In [53]:

img_data = []
for i in range(0,r-1):
  img1 = np.zeros((m-2*i,n-2*i),dtype = np.uint8)
  img1[0,:] = img[i,i:n-i]
  img1[m-2*i-1,:] = img[m-i-1,i:n-i]
  img1[:,0] = img[i:m-i,i]
  img1[:,n-2*i-1] = img[i:m-i,n-i-1]
  img_data.append(img1)
print(img_data[r-2])

[[ 51  76  74  67  83  71  83  92  71  84  79  75  90  91  79  82  58  38
   33  45  35  63  69  40  32  57  79  85  93  90 100  96 104  97  90  90
   80  66  62  56  46  41  38  35  44  66  49  57  66  58  53  55  50  45
   78  72  90  83 100  97 101 103 120 135 145 131 119  80 125  82  33  96
  116  80  40  32  30  25  48  40  21  37  33  51  81  51  57  66  68  69
   83  58  42  39  50  50  56  41  44  37  35  35  27  41]
 [ 63   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0  45]
 [ 67   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

In [54]:
#Achieving the last matrix img_data[r-1]

if m<=n and m%2 == 1:
  img1 = np.zeros((1,n-m+1),dtype = np.uint8) #create a temporary variable to store the array
  img1 = img[r-1,r-1:r+n-m]   #corrected index
  img_data.append(img1) #append this new array to img_data
elif m<=n and m%2 == 0:
  img1 = np.zeros((2,n-m+2),dtype = np.uint8) #create a temporary variable to store the array
  img1[0,:] = img[r-1,r-1:r+n-m+1]
  img1[1,:] = img[r,r-1:r+n-m+1]    #corrected index
  img_data.append(img1) #append this new array to img_data

elif m>n and n%2 == 1:
  img1 = np.zeros((m-n+1,1),dtype = np.uint8) #create a temporary variable to store the array
  img1 = img[r-1:r+m-n,r-1] # corrected index, column is r-1 in this case
  img_data.append(img1) # Append to img_data
elif m>n and n%2 == 0:
  img1 = np.zeros((m-n+2,2),dtype = np.uint8) #create a temporary variable to store the array
  img1[:,0] = img[r-1:r+m-n+1,r-1]  # corrected index, column is r-1
  img1[:,1] = img[r-1:r+m-n+1,r]  # corrected index, column is r
  img_data.append(img1) # Append to img_data

print(img_data[r-1].shape) # Accessing the last element after appending it
print(img_data[r-1])

(2, 102)
[[ 74  74  63  82  66  72  79  74  67  60  74  79  63  64  59  57  43  28
   31  47  62  48  59  66  56  38  54  38  75  94  90  62  77  64  66  66
   48  50  37  37  39  48  50  47  50  64  65  61  56  48  51  64  70  90
  104  83  97 100 102 108 117 128 124 133 139 103  69 109  98  21  33  32
   39  43  34  23  28  17  19  24 135  35  33  79  76  52  67  67  81  64
   38  50  53  67  69  59  47  51  54  47  50  42]
 [ 64  55  74  76  76  79  46  46  41  39  42  39  41  47  40  44  27  30
   23  37  56  50  41  48  34  41  40  40  51  60  47  60  60  51  43  49
   35  52  52  55  57  62  69  68  59  66  72  84  60  65  61  73  95 126
  122 132 108 124 111  97 116 116 130 128 120  97  57  22  30  36  42  48
   49  42  46  28  18  13  14 189 154 147 181 176  82  83  64  68  78  46
   53  56  58  59  79  50  49  48  51  54  53  48]]


In [55]:
# Traversal of matrices img_data[0],img_data[1],img_data[2]....img_data[r-2]
# this traversal is using np array element
img_1 = []
for i in range(0,r-1):
    [m,n] = img_data[i].shape
    #matrix traversal in clockwise direction or in spiral form
    arr1 = np.array(img_data[i][:,0])               #this is the first column of the matrix
    arr2 = np.array(img_data[i][m-1,1:n-1])         #this is the last row in which first and last element are not present(since we don't need them)
    arr3 = np.array(img_data[i][m-1::-1,n-1])       #this the last column of the matrix in which elements are from bottom to top
    arr4 = np.array(img_data[i][0,n-2:0:-1])        #this is the first row in which elements are from right to left
    new_arr1 = np.empty((0,),dtype = np.uint8)       #we created an array of length 0 for joining the elements of first and last row
    new_arr2 = np.empty((0,),dtype= np.uint8)        #here also we created another array for joining the elements of last and first row
    for i in range(len(arr1)):
        new_arr1 = np.append(new_arr1,[arr1[i],arr3[i]])       #here we append the elements of first and last column one after another
    for i in range(len(arr2)):
        new_arr2 = np.append(new_arr2,[arr2[i],arr4[i]])       #here we append the elements of last and first row one after another
    new_arr = np.concatenate((new_arr1,new_arr2))              #here we concatenate both the arrays into single array
    img_1.append(new_arr)                                      #append the array into a list
print(img_1[r-2]) 

[ 51  48  63  48  67  45  70  41  66  27  71  35  74  35  66  37  66  44
  59  41  58  56  58  50  71  50  52  39  64  42  45  58  40  83  43  69
  50  68  41  66  42  57  48  51  36  81  39  51  36  33  33  37  34  21
  40  40  33  48  43  25  44  30  37  32  49  40  44  80  47 116  43  96
  28  33  36  82  43 125  60  80  48 119  57 131  71 145  69 135  55 120
  67 103  81 101  60  97  67 100  67  83  91  90  71  72  73  78  85  45
  84  50  84  55 130  53 129  58 134  66 128  57 104  49 118  66 121  44
 127  35 115  38 130  41 112  46 130  56 101  62  36  66  20  80  24  90
  26  90  32  97  49 104  41  96  25 100  19  90  19  93  17  85  16  79
  13  57  96  32 149  40 168  69 206  63 179  35 213  45 182  33  52  38
  47  58  42  82  34  79  40  91  53  90  69  75  52  79  68  84  54  71
  52  92  52  83  44  71  58  83  54  67  54  74  43  76]


In [56]:
#traversal and reshuffling the last matrix img_data[r-1]
#define the size of last matrix r-1
if img_data[r-1].ndim == 1:
    m,n = 1,img_data[r-1].shape[0]
else:
    m,n = img_data[r-1].shape[0],img_data[r-1].shape[1]
print(m,n)
                      
if m ==1 :            #or you can add one case also here that is (if  m=1 and n=1
  shuffled_row = np.empty((2*n,),dtype = np.uint8)
  shuffled_row[0::2] = img_data[r-1]     # Elements from original row
  shuffled_row[1::2] = img_data[r-1][::-1]  # Elements from reversed row
  img_1.append(shuffled_row[:n])            #take first n elements and append them to the img_1

#  ---------important----------------
#here we are not considering n = 1 case because in numpy array 1-D array same for row and column

elif m ==2 or n==2 :
  arr1 = np.array(img_data[r-1][:,0])               #this is the first column of the matrix
  arr2 = np.array(img_data[r-1][m-1,1:n-1])         #this is the last row in which first and last element are not present(since we don't need them)
  arr3 = np.array(img_data[r-1][m-1::-1,n-1])       #this the last column of the matrix in which elements are from bottom to top
  arr4 = np.array(img_data[r-1][0,n-2:0:-1])        #this is the first row in which elements are from right to left
  new_arr1 = np.empty((0,),dtype = np.uint8)       #we created a array of length 0 for joining the elements of first and last row
  new_arr2 = np.empty((0,),dtype= np.uint8)        #here also we created another array for joining the elements of last and first row
  for i in range(len(arr1)):
    new_arr1 = np.append(new_arr1,[arr1[i],arr3[i]])       #here we append the elements of first and last column one after another
  for i in range(len(arr2)):
    new_arr2 = np.append(new_arr2,[arr2[i],arr4[i]])       #here we append the elements of last and first row one after another
  new_arr = np.concatenate((new_arr1,new_arr2))
  img_1.append(new_arr)
    
print(img_1[r-1].shape)
print(img_1[r-1])

2 102
(204,)
[ 74  48  64  42  55  50  74  47  76  54  76  51  79  47  46  59  46  69
  41  67  39  53  42  50  39  38  41  64  47  81  40  67  44  67  27  52
  30  76  23  79  37  33  56  35  50 135  41  24  48  19  34  17  41  28
  40  23  40  34  51  43  60  39  47  32  60  33  60  21  51  98  43 109
  49  69  35 103  52 139  52 133  55 124  57 128  62 117  69 108  68 102
  59 100  66  97  72  83  84 104  60  90  65  70  61  64  73  51  95  48
 126  56 122  61 132  65 108  64 124  50 111  47  97  50 116  48 116  39
 130  37 128  37 120  50  97  48  57  66  22  66  30  64  36  77  42  62
  48  90  49  94  42  75  46  38  28  54  18  38  13  56  14  66 189  59
 154  48 147  62 181  47 176  31  82  28  83  43  64  57  68  59  78  64
  46  63  53  79  56  74  58  60  59  67  79  74  50  79  49  72  48  66
  51  82  54  63  53  74]


In [80]:
#combimation of matrices of matrices img_1[0],img_1[1],img_1[2] .....img_1[r-1]
m,n = img.shape
total_elements = m*n
all_elements = np.concatenate(img_1)
img_2 = all_elements.reshape(n,m,order = 'F')
print(img_2)
print(img_2.shape)

[[ 13  50  13 ...  69  70 126]
 [ 73  91  12 ... 110 145  72]
 [ 15  53  29 ...  62  79 127]
 ...
 [ 98   9  39 ... 100  42  63]
 [ 70  17  21 ...  75 122  53]
 [113   9  34 ... 136  55  74]]
(500, 400)


In [82]:
# rotation of img_2 counterclockwise 90 degree to get img_3
img_3 = np.rot90(img_2 ,k = 1)  # k is the no. of times to rotate by 90 degree 
print(img_3)
print(img_3.shape)
# cv2.imwrite('scr.png',img_3)
# cv2.imshow("first scramble", img_3)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

[[126  72 127 ...  63  53  74]
 [ 70 145  79 ...  42 122  55]
 [ 69 110  62 ... 100  75 136]
 ...
 [ 13  12  29 ...  39  21  34]
 [ 50  91  53 ...   9  17   9]
 [ 13  73  15 ...  98  70 113]]
(400, 500)


True